# Generated by Django 4.2.4 on 2023-08-29 02:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(null=True, upload_to='adjuntos/')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título de la solicitud a levantar', max_length=300, verbose_name='Título')),
                ('lista_desplegable', models.CharField(choices=[('Reporte de problema', 'Reporte de problema'), ('Solicitud de informacion', 'Solicitud de informacion')], default='Reporte de problema', max_length=50, verbose_name='Tipo de solicitud')),
                ('fecha_reporte', models.DateField(default=datetime.datetime.today, verbose_name='Fecha del reporte')),
                ('descripcion', models.CharField(default='Describa la solicitud a enviar', max_length=500)),
                ('adjuntos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DMU.adjuntos')),
            ],
            options={
                'verbose_name': 'Solicitudes',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
